# Generated by Django 4.1 on 2022-08-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('vat', models.CharField(blank=True, max_length=15, null=True, verbose_name='VAT')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone')),
                ('mobil', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobil phone')),
                ('email', models.EmailField(max_length=255, verbose_name='Main email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('state_client', models.CharField(choices=[('Activo', 'Activo'), ('Baja', 'Baja'), ('Bloqueado', 'Bloqueado')], default='Activo', max_length=50, null=True, verbose_name='State')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
